"""
Email Notification System for Network Troubleshooting Bot
Sends email alerts for network issues and troubleshooting results
"""
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os
from datetime import datetime
from typing import List, Optional, Dict, Any
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)

@dataclass
class EmailConfig:
    smtp_server: str
    smtp_port: int
    username: str
    password: str
    from_address: str
    use_tls: bool = True

@dataclass
class EmailAlert:
    to_addresses: List[str]
    subject: str
    message: str
    html_message: Optional[str] = None
    priority: str = "normal"  # low, normal, high, urgent
    attachments: Optional[List[str]] = None

class EmailNotifier:
    def __init__(self, config: EmailConfig):
        self.config = config
    
    async def send_alert(self, alert: EmailAlert) -> bool:
        """Send email alert"""
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['From'] = self.config.from_address
            msg['To'] = ', '.join(alert.to_addresses)
            msg['Subject'] = alert.subject
            
            # Set priority
            if alert.priority == "high":
                msg['X-Priority'] = '2'
            elif alert.priority == "urgent":
                msg['X-Priority'] = '1'
            elif alert.priority == "low":
                msg['X-Priority'] = '4'
            else:
                msg['X-Priority'] = '3'
            
            # Add timestamp
            msg['Date'] = datetime.now().strftime("%a, %d %b %Y %H:%M:%S %z")
            
            # Add plain text part
            text_part = MIMEText(alert.message, 'plain')
            msg.attach(text_part)
            
            # Add HTML part if provided
            if alert.html_message:
                html_part = MIMEText(alert.html_message, 'html')
                msg.attach(html_part)
            
            # Add attachments if provided
            if alert.attachments:
                for file_path in alert.attachments:
                    if os.path.exists(file_path):
                        with open(file_path, 'rb') as attachment:
                            part = MIMEBase('application', 'octet-stream')
                            part.set_payload(attachment.read())
                        
                        encoders.encode_base64(part)
                        part.add_header(
                            'Content-Disposition',
                            f'attachment; filename= {os.path.basename(file_path)}'
                        )
                        msg.attach(part)
            
            # Send email
            context = ssl.create_default_context()
            
            with smtplib.SMTP(self.config.smtp_server, self.config.smtp_port) as server:
                if self.config.use_tls:
                    server.starttls(context=context)
                
                server.login(self.config.username, self.config.password)
                
                text = msg.as_string()
                server.sendmail(self.config.from_address, alert.to_addresses, text)
            
            logger.info(f"Email sent successfully to {', '.join(alert.to_addresses)}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email: {str(e)}")
            return False
    
    def create_network_alert_email(self, alert_type: str, device: str, 
                                 details: Dict[str, Any], severity: str = "medium") -> EmailAlert:
        """Create a formatted network alert email"""
        
        # Generate subject
        subject_prefix = {
            "critical": "🚨 CRITICAL",
            "high": "⚠️ HIGH",
            "medium": "⚠️ ALERT",
            "low": "ℹ️ INFO"
        }.get(severity, "⚠️ ALERT")
        
        subject = f"{subject_prefix}: Network {alert_type} - {device}"
        
        # Generate message
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        message = f"""
Network Troubleshooting Bot Alert

Alert Type: {alert_type}
Device: {device}
Severity: {severity.upper()}
Timestamp: {timestamp}

Details:
"""
        
        for key, value in details.items():
            message += f"  {key}: {value}\n"
        
        message += f"""
---
This alert was generated by Network Troubleshooting Bot.
Please investigate and take appropriate action.
        """
        
        # Generate HTML message
        html_message = f"""
        <html>
        <head></head>
        <body>
            <h2 style="color: {'red' if severity in ['critical', 'high'] else 'orange' if severity == 'medium' else 'blue'};">
                Network Troubleshooting Bot Alert
            </h2>
            
            <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
                <tr>
                    <td><strong>Alert Type</strong></td>
                    <td>{alert_type}</td>
                </tr>
                <tr>
                    <td><strong>Device</strong></td>
                    <td>{device}</td>
                </tr>
                <tr>
                    <td><strong>Severity</strong></td>
                    <td style="color: {'red' if severity in ['critical', 'high'] else 'orange' if severity == 'medium' else 'blue'};">
                        {severity.upper()}
                    </td>
                </tr>
                <tr>
                    <td><strong>Timestamp</strong></td>
                    <td>{timestamp}</td>
                </tr>
            </table>
            
            <h3>Details:</h3>
            <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
        """
        
        for key, value in details.items():
            html_message += f"""
                <tr>
                    <td><strong>{key}</strong></td>
                    <td>{value}</td>
                </tr>
            """
        
        html_message += """
            </table>
            
            <hr>
            <p><em>This alert was generated by Network Troubleshooting Bot.</em></p>
            <p><em>Please investigate and take appropriate action.</em></p>
        </body>
        </html>
        """
        
        priority = "urgent" if severity == "critical" else "high" if severity == "high" else "normal"
        
        return EmailAlert(
            to_addresses=[],  # Will be set by caller
            subject=subject,
            message=message.strip(),
            html_message=html_message,
            priority=priority
        )
    
    def create_ping_failure_alert(self, target: str, packet_loss: float, 
                                avg_latency: Optional[float] = None) -> EmailAlert:
        """Create ping failure alert email"""
        
        details = {
            "Target": target,
            "Packet Loss": f"{packet_loss}%"
        }
        
        if avg_latency is not None:
            details["Average Latency"] = f"{avg_latency:.2f}ms"
        
        severity = "critical" if packet_loss >= 50 else "high" if packet_loss >= 20 else "medium"
        
        return self.create_network_alert_email("Ping Failure", target, details, severity)
    
    def create_interface_down_alert(self, device: str, interface: str, 
                                  duration: Optional[str] = None) -> EmailAlert:
        """Create interface down alert email"""
        
        details = {
            "Interface": interface,
            "Status": "DOWN"
        }
        
        if duration:
            details["Down Duration"] = duration
        
        return self.create_network_alert_email("Interface Down", device, details, "high")
    
    def create_high_cpu_alert(self, device: str, cpu_usage: float, 
                            threshold: float = 90) -> EmailAlert:
        """Create high CPU usage alert email"""
        
        details = {
            "CPU Usage": f"{cpu_usage:.1f}%",
            "Threshold": f"{threshold}%",
            "Exceeded By": f"{cpu_usage - threshold:.1f}%"
        }
        
        severity = "critical" if cpu_usage >= 95 else "high"
        
        return self.create_network_alert_email("High CPU Usage", device, details, severity)
    
    def create_device_unreachable_alert(self, device: str, last_seen: Optional[str] = None) -> EmailAlert:
        """Create device unreachable alert email"""
        
        details = {
            "Status": "UNREACHABLE",
            "Last Ping": "Failed"
        }
        
        if last_seen:
            details["Last Seen"] = last_seen
        
        return self.create_network_alert_email("Device Unreachable", device, details, "critical")
    
    def create_troubleshooting_summary_email(self, session_id: str, issues_found: List[Dict[str, Any]], 
                                          actions_taken: List[Dict[str, Any]]) -> EmailAlert:
        """Create troubleshooting session summary email"""
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        subject = f"Troubleshooting Summary - Session {session_id}"
        
        message = f"""
Network Troubleshooting Session Summary

Session ID: {session_id}
Timestamp: {timestamp}

Issues Found ({len(issues_found)}):
"""
        
        for i, issue in enumerate(issues_found, 1):
            message += f"  {i}. {issue.get('description', 'Unknown issue')}\n"
            message += f"     Severity: {issue.get('severity', 'Unknown')}\n"
            message += f"     Device: {issue.get('device', 'Unknown')}\n\n"
        
        message += f"\nActions Taken ({len(actions_taken)}):\n"
        
        for i, action in enumerate(actions_taken, 1):
            message += f"  {i}. {action.get('description', 'Unknown action')}\n"
            message += f"     Status: {action.get('status', 'Unknown')}\n"
            message += f"     Result: {action.get('result', 'Unknown')}\n\n"
        
        message += """
---
Network Troubleshooting Bot Session Complete
        """
        
        # Generate HTML version
        html_message = f"""
        <html>
        <head></head>
        <body>
            <h2>Network Troubleshooting Session Summary</h2>
            
            <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
                <tr>
                    <td><strong>Session ID</strong></td>
                    <td>{session_id}</td>
                </tr>
                <tr>
                    <td><strong>Timestamp</strong></td>
                    <td>{timestamp}</td>
                </tr>
            </table>
            
            <h3>Issues Found ({len(issues_found)}):</h3>
            <ol>
        """
        
        for issue in issues_found:
            severity_color = {
                'critical': 'red',
                'high': 'orange',
                'medium': 'blue',
                'low': 'green'
            }.get(issue.get('severity', '').lower(), 'black')
            
            html_message += f"""
                <li>
                    <strong>{issue.get('description', 'Unknown issue')}</strong><br>
                    Severity: <span style="color: {severity_color};">{issue.get('severity', 'Unknown')}</span><br>
                    Device: {issue.get('device', 'Unknown')}
                </li>
            """
        
        html_message += f"""
            </ol>
            
            <h3>Actions Taken ({len(actions_taken)}):</h3>
            <ol>
        """
        
        for action in actions_taken:
            status_color = 'green' if action.get('status') == 'success' else 'red'
            
            html_message += f"""
                <li>
                    <strong>{action.get('description', 'Unknown action')}</strong><br>
                    Status: <span style="color: {status_color};">{action.get('status', 'Unknown')}</span><br>
                    Result: {action.get('result', 'Unknown')}
                </li>
            """
        
        html_message += """
            </ol>
            
            <hr>
            <p><em>Network Troubleshooting Bot Session Complete</em></p>
        </body>
        </html>
        """
        
        return EmailAlert(
            to_addresses=[],  # Will be set by caller
            subject=subject,
            message=message.strip(),
            html_message=html_message,
            priority="normal"
        )

# Convenience functions
def create_email_notifier_from_config(config_dict: Dict[str, Any]) -> EmailNotifier:
    """Create EmailNotifier from configuration dictionary"""
    email_config = EmailConfig(
        smtp_server=config_dict.get('smtp_server', 'smtp.gmail.com'),
        smtp_port=config_dict.get('smtp_port', 587),
        username=config_dict.get('username', ''),
        password=config_dict.get('password', ''),
        from_address=config_dict.get('from_address', ''),
        use_tls=config_dict.get('use_tls', True)
    )
    
    return EmailNotifier(email_config)

async def send_quick_alert(smtp_server: str, username: str, password: str, 
                          from_address: str, to_addresses: List[str], 
                          subject: str, message: str) -> bool:
    """Quick function to send an alert email"""
    config = EmailConfig(
        smtp_server=smtp_server,
        smtp_port=587,
        username=username,
        password=password,
        from_address=from_address
    )
    
    notifier = EmailNotifier(config)
    alert = EmailAlert(
        to_addresses=to_addresses,
        subject=subject,
        message=message
    )
    
    return await notifier.send_alert(alert)